version: "3.9"
services:
  nginx:
    ports:
      - 8000:80
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_UPSTREAMS: http://app/
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:8000/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: winebarrel.jp
    env_file:
      - oauth2-proxy.env
  app:
    image: ruby:2.7
    command:
      - ruby
      - -rwebrick
      - -e
      - "WEBrick::HTTPServer.new(Port: 3000).tap {|s| s.mount_proc(?/) {|_, r| r.body = :OK.to_s } }.start"
